name: Update BiS feed

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 horas (UTC)

permissions:
  contents: write

concurrency:
  group: update-bis
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci || npm install --no-fund --no-audit

      # Genera bis-feed.* automáticamente desde Warcraft Logs (WCL)
      - name: Build BiS feed automatically (WCL)
        run: npm run auto:wcl
        env:
          WCL_CLIENT_ID: ${{ secrets.WCL_CLIENT_ID }}
          WCL_CLIENT_SECRET: ${{ secrets.WCL_CLIENT_SECRET }}

      # Genera wow-icons.js desde el CDN de Wowhead (sin API)
      - name: Build icons (static, no API)
        run: npm run icons

      # Sanity check: evita commitear algo roto
      - name: Validate feed
        run: |
          node -e "const fs=require('fs');const f=JSON.parse(fs.readFileSync('bis-feed.json','utf8'));if(!f||!f.data||!Object.keys(f.data).length){console.error('Feed vacío o sin data');process.exit(1)};for(const c of Object.keys(f.data)){for(const s of Object.keys(f.data[c])){if(!Array.isArray(f.data[c][s])){console.error('Spec no es array:',c,s);process.exit(1)}}}"
          test -f bis-feed.js && echo "bis-feed.js OK"
          test -f wow-icons.js && echo "wow-icons.js OK"

      - name: Commit updated feed & icons
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update BiS (WCL) & icons [skip ci]"
          file_pattern: "bis-feed.json bis-feed.js wow-icons.js"
