name: Update BiS feed

on:
  push:
    branches: [ main ]          # cuando edites YAML/HTML
  workflow_dispatch:             # correr a mano
  schedule:
    - cron: "0 */6 * * *"       # cada 6 horas (opcional)

permissions:
  contents: write               # para commitear con el GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build bis-feed.json
        run: npm run update

      - name: Commit updated feed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update BiS feed [skip ci]"
          file_pattern: bis-feed.json bis-feed.js

