name: Update BiS feed

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 horas (UTC)

permissions:
  contents: write

concurrency:
  group: update-bis
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # sin cache para que no exija lockfile

      - name: Install deps
        run: npm install --no-fund --no-audit

      # Genera bis-feed.json y bis-feed.js desde data/bis-source.yaml
      - name: Build BiS feed (JSON + JS)
        run: npm run update

      # Genera wow-icons.js usando la API de Blizzard (solo si hay secrets)
      - name: Build icons (Blizzard)
        if: ${{ secrets.BLIZZARD_CLIENT_ID && secrets.BLIZZARD_CLIENT_SECRET }}
        run: npm run icons
        env:
          BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
          BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
          BLIZZARD_REGION: us
          BLIZZARD_LOCALE: es_MX

      # Sanity check: evita commitear un feed vacío
      - name: Validate feed
        run: node -e "const fs=require('fs'); const f=JSON.parse(fs.readFileSync('./bis-feed.json','utf8')); if(!f?.data||!Object.keys(f.data).length){console.error('Feed vacío');process.exit(1)}"

      - name: Commit updated feed & icons
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update BiS feed & icons [skip ci]"
          file_pattern: "bis-feed.json bis-feed.js wow-icons.js"
